# Copyright (c) 2017 Michael Heilmann

# Require sudo (to install software).
sudo: required
# Select Ubuntu 'Trusty'.
dist: trusty

# Compile once for Clang and once for GCC.
compiler:
    - clang
    - gcc
    
addons:
    apt:
        sources:
            # add PPAs with more up-to-date toolchains
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            # GCC 6
            - gcc-6
            - g++-6
            # CLANG 3.8
            - clang-3.8
            #- libc++-dev
            # PhysFS
            #- libphysfs-dev
            # SDL 2
            #- libsdl2-dev
            #- libsdl2-image-dev
            #- libsdl2-mixer-dev
            #- libsdl2-ttf-dev
            # CMake (outdated)
            - cmake
            
before_install:
- if [ "$CC" = "clang" ]; then 
      export CC="clang-3.8" CXX="clang++-3.8" CXXFLAGS="-ftemplate-depth=1024";
  else
      export CC="gcc-6" CXX="g++-6";
  fi
  
# Download and install CMake.
install:
# Create a dependency directory. Store its path in `${DEPS_DIR}`.
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
# Download CMake 3.9.3 binary into `${DEPS_DIR}/cmake`.
# Unpack it and export its binary directory to path.
- |
  CMAKE_BIN_URL="https://cmake.org/files/v3.9/cmake-3.9.3-Linux-x86_64.tar.gz"
  mkdir -p cmake-bin
  cd cmake-bin
  wget --no-check-certificate -O - -q "${CMAKE_BIN_URL}" | tar xsz --strip-components=1 -f -
  cd ..
  export PATH="${DEPS_DIR}/cmake-bin/bin:${PATH}"

before_script:  
- export CC=gcc-6
- export CXX=g++-6
# Log the versions of the C and C++ compiler, log the version of CMake. 
#- gcc -v
#- g++ -v
# cmake --version
# Run CMake.
- cd "${TRAVIS_BUILD_DIR}"
- cmake CMakeLists.txt

script:
# Enter the Travis build directory.
- cd "${TRAVIS_BUILD_DIR}"
# Run "make all" and "make test".
- make all && make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/deeca47d07972d6be9c3
      - https://webhooks.gitter.im/e/b8067a6aaf118ec7e6a1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
